name: Run Daily Batter vs Pitch Analysis

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 12:00 UTC (8 AM Eastern)
  workflow_dispatch:       # Allows you to trigger it manually

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py
